[package]

name = "rust-net-misc"
version = "0.0.1"
authors = [ "Anson Rosenthal <anson.rosenthal@gmail.com>"
          , "John Ericson <Ericson2314@Yahoo.com>" ]

[lib]
name = "misc"

[dependencies.log_ng]
git = "https://github.com/sfackler/log-ng.git"

