[package]

name = "rust-net-transport-tcp"
version = "0.0.1"
authors = [ "Anson Rosenthal <anson.rosenthal@gmail.com>"
          , "John Ericson <Ericson2314@Yahoo.com>" ]

[lib]
name = "tcp"


[dependencies.rust-net-misc]
path = "../../misc"

[dependencies.rust-net-network]
path = "../../network"
